package VIEW;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

public class purchaseView extends JFrame {
    private JLabel dealid;
    private JLabel dealname;
    private JLabel dealgoodid;
    private JLabel dealcount;
    private JLabel dealgoodname;
    private JLabel producetime;
    private JLabel deadline;
    private JTextField tdealid;
    private JTextField tdealname;
    private JTextField tdealgoodid;
    private JTextField tdealcount;
    private JTextField tdealgoodname;
    private JTextField tproducetime;
    private JTextField tdeadline;
    private JButton save;
    private JButton exit;
    public int width = Toolkit.getDefaultToolkit().getScreenSize().width;
    public int height = Toolkit.getDefaultToolkit().getScreenSize().height;
    public int windowsWedth = 600;
    public int windowsHeight = 400;
    public purchaseView(){
        getContentPane().setLayout(null);
        this.setTitle("进货管理");
        this.setVisible(true);
        int x = (width - windowsWedth) / 2;
        int y = (height - windowsHeight) / 2;
        this.setBounds(x, y, windowsWedth, windowsHeight);
        dealid = new JLabel("供货商编号:");
        dealid.setFont(new Font("", Font.BOLD, 35));
        dealid.setBounds(100, 10, 100, 40);
        dealname = new JLabel("供货商名称:");
        dealname.setBounds(100, 60, 100, 40);
        dealname.setFont(new Font("", Font.BOLD, 35));
        dealgoodid = new JLabel("商品编号:");
        dealgoodid.setBounds(100, 110, 100, 40);
        dealgoodid.setFont(new Font("", Font.BOLD, 35));
        dealcount=new JLabel("商品数量:");
        dealcount.setBounds(100,160,100,40);
        dealcount.setFont(new Font("",Font.BOLD,35));
        dealgoodname=new JLabel("商品名称");
        dealgoodname.setBounds(100,210,100,40);
        dealgoodname.setFont(new Font("",Font.BOLD,35));
        producetime=new JLabel("生产日期:");
        producetime.setBounds(100,260,100,40);
        producetime.setFont(new Font("",Font.BOLD,35));
        deadline=new JLabel("有效日期:");
        deadline.setBounds(100,310,100,40);
        deadline.setFont(new Font("",Font.BOLD,35));
        save = new JButton("保存");
        save.setBounds(305, 200, 200, 60);
        save.setFont(new Font("", Font.BOLD, 50));
        save.addActionListener((ActionListener) this);
        save.setBackground(new Color(0,127,127));
        exit = new JButton("退出");
        exit.setBounds(305, 200, 200, 60);
        exit.setFont(new Font("", Font.BOLD, 50));
        exit.addActionListener((ActionListener) this);
        exit.setBackground(new Color(0,127,127));
        getContentPane().add(dealgoodname);
        getContentPane().add(dealname);
        getContentPane().add(dealcount);
        getContentPane().add(dealgoodid);
        getContentPane().add(dealid);
        getContentPane().add(producetime);
        getContentPane().add(deadline);
        getContentPane().add(save);
        getContentPane().add(exit);
    }
}
